name: Build

on:
  repository_dispatch:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: echo github actor
        run: echo ${{ github.actor }}

      - name: Checkout code
        uses: actions/checkout@v2
